# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-04 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edition',
            fields=[
                ('Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='grade',
            fields=[
                ('gradeId', models.IntegerField(primary_key=True, serialize=False)),
                ('gradeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='knowledge_basic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('knowledgeName', models.CharField(max_length=200, verbose_name='知识点名称')),
                ('key', models.CharField(max_length=500)),
                ('descs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='pharse',
            fields=[
                ('pharseId', models.IntegerField(primary_key=True, serialize=False)),
                ('pharseName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('subjectId', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=255)),
                ('pinyin', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='knowledge_basic',
            name='pharseId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pharse', verbose_name='学历Id'),
        ),
        migrations.AddField(
            model_name='knowledge_basic',
            name='subjectId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='学科ID'),
        ),
    ]
